import { Metadata } from 'next'
// import { getCart } from '@/actions/get-cart'
import { Divider } from '@heroui/react'
//import CartBreadcrumb from './components/cart-breadcrumb'
// import CartNotFound from './components/cart-not-found'
// import CartItem from './components/cart-item'
// import CartSummary from './components/cart-summary'
import Footer from '@/components/layouts/footer'
// import LoadingOverlay from '@/components/loading-overlay'
import Cart from './components/cart'

export const metadata: Metadata = {
  title: 'Giỏ Hàng',
  description: 'Generated by create next app'
}

const CartPage = async () => {
  return (
    <div>
      <Cart />
      <Divider />
      <Footer />
    </div>
  )
}

export default CartPage
