import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'
import { Header } from '@/components/layouts/header'
import { ToastProvider } from '@/providers/toast-provider'
import AuthProvider from '@/providers/auth-provider'

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin', 'vietnamese']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={openSans.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <ToastProvider />
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </ThemeProvider>
        <ToastProvider />
      </body>
    </html>
  )
}
